version: '3'

services:
  fhir:
    image: openconceptlab/oclfhir:${ENVIRONMENT-production}
    restart: "always"
    command: sh -c "/code/startup.sh"
    ports:
      - ${SERVER_PORT-8080}:${SERVER_PORT-8080}
    environment:
      - ENVIRONMENT=${ENVIRONMENT-dev}
      - DATABASE_URL=${DATABASE_URL-jdbc:postgresql://host.docker.internal:5432/postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD-Postgres123}
      - DATABASE_DIALECT=${DATABASE_DIALECT-org.hibernate.dialect.ProgressDialect}
      - SERVER_PORT=${SERVER_PORT-8080}
      - OCL_SERVLET_BASEURL=${OCL_SERVLET_BASEURL-http://localhost:8080/fhir}
